import { StyleSheet } from "react-native";
import codegenNativeCommands from "react-native/Libraries/Utilities/codegenNativeCommands";

const styles = StyleSheet.create({
  centeredView: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    width: "100%",
    backgroundColor: "rgba(52, 52, 52, 0.8)",
  },
  gameCreateCenteredView: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "center",
    height: "100%",
    width: "100%",
  },
  modalView: {
    display: "flex",
    flexDirection: "column",
    height: "30%",
    width: "85%",
    backgroundColor: "white",
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  gameCreateModalView: {
    display: "flex",
    flexDirection: "column",
    height: "85%",
    width: "100%",
    backgroundColor: "white",
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  confirmationContainer: {
    display: "flex",
    flexDirection: "row",
    height: "20%",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
  },
  gameCreateConfirmationContainer: {
    display: "flex",
    flexDirection: "row",
    height: "10%",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
  },
  gameCreatePlayerInfoContainer: {
    display: "flex",
    flexDirection: "column",
    height: "30%",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  playerInfoLabel: {
    color: "#666",
    fontSize: 24,
    fontStyle: "normal",
    fontWeight: 500,
  },
  gameCreateLabelContainer: {
    display: "flex",
    height: "20%",
    width: "100%",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  gameCreateDividedContaier: {
    display: "flex",
    height: "80%",
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  playerLabel: {
    color: "#666",
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: 400,
  },
  gameCreateLeftContainer: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    width: "50%",
    alignItems: "center",
    justifyContent: "center",
  },
  gameCreateRightContainer: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    width: "50%",
    alignItems: "center",
    justifyContent: "center",
  },
  gameCreateButtonContainer: {
    display: "flex",
    flexDirection: "column",
    height: "25%",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmationButton: {
    display: "flex",
    flexDirection: "column",
    height: "90%",
    width: "20%",
    alignItems: "center",
    justifyContent: "center",
  },
  textStyle: {
    color: "#275b97ff",
    fontWeight: "bold",
    textAlign: "center",
  },
  holeSelectorContainer: {
    display: "flex",
    flexDirection: "column",
    height: "20%",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  scoreModalView: {
    display: "flex",
    flexDirection: "column",
    height: "65%",
    width: "90%",
    backgroundColor: "white",
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  scoreConfirmationContainer: {
    display: "flex",
    flexDirection: "row",
    height: "8%",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitleContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "10%",
  },
  courseNameLabel: {
    color: "#5e5e5eff",
    fontSize: 18,
    fontWeight: 500,
  },
  dateLabel: {
    color: "#5e5e5eff",
    fontSize: 14,
    fontWeight: 500,
  },
});

export default styles;
