import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  mainContainer: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    width: "100%",
    paddingLeft: 15,
    paddingRight: 15,
    paddingTop: 15,
  },
  weatherContainer: {
    display: "flex",
    flexDirection: "row",
    height: "20%",
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(202, 202, 202, 0.22)",
  },
  cloudContainer: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    width: "48%",
    justifyContent: "center",
    alignItems: "center",
  },
  verticleLine: {
    height: "80%",
    width: 2,
    backgroundColor: "#ffffffff",
  },
  temperatureContainer: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    width: "48%",
    justifyContent: "center",
    alignItems: "center",
  },
  topDetailsContainer: {
    display: "flex",
    flexDirection: "column",
    height: "20%",
    width: "100%",
    justifyContent: "center",
    alignItems: "flex-end",
    paddingRight: 10,
  },
  moreDetailsLabel: {
    color: "#9c9c9cff",
    fontSize: 13,
    fontStyle: "normal",
    fontWeight: "500",
  },
  middleTempContainer: {
    display: "flex",
    flexDirection: "column",
    height: "55%",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  tempLabel: {
    color: "#666",
    fontSize: 35,
    fontStyle: "normal",
    fontWeight: "500",
  },
  bottomTempContainer: {
    display: "flex",
    flexDirection: "row",
    height: "25%",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  weatherLabelContainer: {
    display: "flex",
    flexDirection: "row",
    height: "100%",
    width: "25%",
    alignItems: "center",
    justifyContent: "center",
  },
  weatherLabel: {
    color: "#666",
    fontSize: 10,
    fontStyle: "normal",
    fontWeight: 400,
  },
  weatherLogo: {
    height: "30%",
    width: "30%",
  },
  topLocationContainer: {
    display: "flex",
    flexDirection: "column",
    height: "20%",
    width: "100%",
    justifyContent: "center",
    alignItems: "flex-end",
    paddingRight: 10,
  },
  middleCloudContainer: {
    display: "flex",
    flexDirection: "column",
    height: "55%",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  bottomCloudContainer: {
    display: "flex",
    flexDirection: "row",
    height: "25%",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  dropdown: {
    height: "100%",
    width: "100%",
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  placeholderStyle: {
    fontSize: 13,
    color: "#9c9c9cff",
  },
  selectedTextStyle: {
    fontSize: 10,
    color: "#9c9c9cff",
  },
  inputSearchStyle: {
    height: 25,
    fontSize: 14,
  },
  itemTextStyle: {
    color: "#666666",
    fontSize: 15,
  },
});

export default styles;
